version: '2'
services:
  db:
    restart: always
    image: postgres:9.5.3 
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - "./.pgdata:/var/lib/postgresql/data"
    networks:
      - odoo

  odoo8:
    restart: always
    image: odoo:9.0
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "8069:8069"
    volumes:
      - "./config:/etc/odoo"
      - "./custom:/custom"
      - "./.var/data/odoo:/var/lib/odoo"
    networks:
      - odoo
    command:
      -- -c /etc/odoo/openerp-server.conf 
       
networks:
  odoo:
